# Generated by Django 5.2.4 on 2025-07-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cost_per_month', models.BigIntegerField()),
                ('duration_per_lesson', models.TimeField()),
                ('length', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('lesson_per_week', models.SmallIntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Completed'), (3, 'Closed'), (4, 'On hold')])),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.class')),
                ('student', models.ManyToManyField(related_name='student_group', to='student.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Excused')])),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.student')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.group')),
            ],
        ),
    ]
