# Generated by Django 5.2.4 on 2025-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('born_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=150)),
                ('dad_number', models.CharField(max_length=150)),
                ('mum_number', models.CharField(max_length=150)),
                ('join_date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Graduated'), (4, 'On hold')], default=1)),
            ],
        ),
    ]
