# Generated by Django 5.2.4 on 2025-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.SmallIntegerField()),
                ('phone_number', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('fixed_salary', models.BooleanField(default=True)),
                ('salary', models.BigIntegerField()),
                ('percentage', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(1, 'Working'), (2, 'On holiday'), (3, 'Fired'), (4, 'Sick'), (5, 'Not working')], default=1)),
            ],
        ),
    ]
